// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoudnhbhehdulfjbgcwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvdWRuaGJoZWhkdWxmamJnY3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NzczNDAsImV4cCI6MjA3MjM1MzM0MH0.CxcMnewIqTBh8RO7EYuYeHL9zE69LpSwxcCdvy-oH-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});